tasks:
  - before: npm install
  - init: npm run build
    command: npm run start

github:
  prebuilds:
    master: true
    branches: true
    addCheck: true
    addComment: false
    addBadge: true
    pullRequests: true
    pullRequestsFromForks: true
