name: Node.js CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Nodejs CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 17.x

      - name: Install Dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build
        
